SRC = $(DIR)/framework/tests/

all: data_manager_unit_test.o
	$(CC) -o DataManagerUnitTest $(ODIR)/data_manager_unit_test.o 

data_manager_unit_test.o:
	$(CC) -c $(SRC)DataManagerUnitTest.cpp -o $(ODIR)/data_manager_unit_test.o

clean:

